- .github/workflows/codecov.yaml
- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- Makefile
- sonar-project.properties
- tests/e2e/capsule-feature/02-install-operator.yaml
- tests/e2e/clustersecret/00-install-operator.yaml
Please include a summary of the change and why it is needed.
Fixes # (issue)
Add any other context or screenshots about the feature request here.
> chore: Migrate from gerrit to github pipelines

- hack/install-kuttl.sh
We need to update kuttle to the latest stable version
Fixes # (issue)
Add any other context or screenshots about the feature request here.
> chore: Update kuttle to version 0.16 (#44)

- Makefile
We need to use cache to speed-up CI for helm-docs command
Add any other context or screenshots about the feature request here.
> chore: Use Go cache for helm-docs (#44)

- Makefile
Update helm-docs to the latest stable version
Fixes #44 
make helm-docs
> chore: Update helm-docs to the latest stable (#44)

- .github/workflows/release.yaml
- README.md
- build.groovy
- code-review.groovy
- create-release.groovy
- deploy-templates/Chart.yaml
- deploy-templates/README.md
- deploy-templates/values.yaml
Renamed the EDP name matches to KubeRocketCI and updated the documentation links.
Fixes #69
> chore: Update KubeRocketCI names and documentation links (#69)

- CHANGELOG.md
This change updates the CHANGELOG.md file with the contents generated by the "make changelog" command.
> docs: Update CHANGELOG md (#73)

- CHANGELOG.md
This change updates the CHANGELOG.md file
> docs: Update changelog file for release notes (#73)

- CHANGELOG.md
- deploy-templates/Chart.yaml
- deploy-templates/README.md
> chore: Update current development version (#80)

- pull_request_template.md
Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #82
> chore: Update Pull Request Template (#82)

- CHANGELOG.md
- deploy-templates/Chart.yaml
- deploy-templates/README.md
> chore: Update current development version (#94)

- deploy-templates/templates/capsule/tenant.yaml
> chore: Update Capsule CRD version

- CHANGELOG.md
- deploy-templates/Chart.yaml
- deploy-templates/README.md
> chore: Update current development version (#108)

- controllers/clustersecret/clustersecret_controller.go
- controllers/clustersecret/clustersecret_controller_test.go
Enhance cluster secret processing with new label handling
Fixes #111 
- Unit tests
> feat: Enhance cluster secret processing with new label handling

- pkg/argocd/argoapplicationset_manager.go
- pkg/argocd/argoapplicationset_manager_test.go
- tests/e2e/capsule-feature/03-assert-cdpipeline-and-stages.yaml
- tests/e2e/capsule-feature/03-create-cdpipeline-and-stages.yaml
Align ApplicationSet to use `semver` versioning
Fixes #122
> chore: Align ApplicationSet to use semver versioning (#122)

- CHANGELOG.md
- deploy-templates/Chart.yaml
- deploy-templates/README.md
> chore: Update current development version (#128)

- deploy-templates/README.md
- deploy-templates/templates/deployment.yaml
- deploy-templates/values.yaml
Add ImagePullSecrets field support in the Helm chart
Fixes #131 
> chore: Add ImagePullSecrets field support (#131)

- controllers/stage/chain/put_codebase_image_stream.go
- controllers/stage/chain/put_codebase_image_stream_test.go
- controllers/stage/stage_controller_test.go
- pkg/platform/config.go
- pkg/platform/config_test.go
- tests/e2e/capsule-feature/00-install-setup.yaml
Rename ConfigMap from 'edp-config' to 'krci-config'
Fixes #124 
- Unit tests
> chore: Rename ConfigMap from 'edp-config' to 'krci-config'

- CHANGELOG.md
- deploy-templates/Chart.yaml
> chore: Update current development version (#133)

- .github/workflows/e2e.yaml
- controllers/stage/chain/delete_environment_label_from_codebase_image_streams_test.go
- controllers/stage/chain/put_codebase_image_stream_test.go
- controllers/stage/chain/put_environment_label_to_codebase_image_streams_test.go
- controllers/stage/chain/remove_labels_from_codebase_docker_streams_test.go
- controllers/stage/stage_controller_test.go
- pkg/util/cluster/cluster.go
- pkg/util/cluster/cluster_test.go
- tests/e2e/capsule-feature/03-create-cdpipeline-and-stages.yaml
Update codebasebranch label to improve consistency
Fixes #135
- Unit test
> refactor: Update codebasebranch label to improve consistency

- pkg/argocd/argoapplicationset_manager.go
- pkg/argocd/argoapplicationset_manager_test.go
- tests/e2e/capsule-feature/03-assert-cdpipeline-and-stages.yaml
Make ApplicationSet generators sorted
Fixes #151 
- Unit tests
- e2e tests
Add any other context or screenshots about the feature request here.
> chore: Make ApplicationSet generators sorted

- CHANGELOG.md
- deploy-templates/Chart.yaml
> chore: Update current development version (#156)

- internal/controller/clustersecret/clustersecret_controller.go
Added error requeue period to prevent continuous reconciliation loops.
Fixes #160 
- Manually
> fix: Improve error handling in ClusterSecret reconciliation (#160)

- .github/workflows/codecov.yaml
> chore: Bump Codecov version (#164)

- CHANGELOG.md
- deploy-templates/Chart.yaml
- deploy-templates/README.md
> chore: Update current development version (#168)
